name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      run: az login

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out main.tfplan

    - name: Terraform Apply
      run: terraform apply -input=false main.tfplan
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'



